[package]
name = "typed-algebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
num = "0.4.1"
syn = { version = "2.0.31", features = ["full"] }
